cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - /vendor

stages:
  - build
  - qa
  - deploy-preprod

build:8.1:
  stage: build
  image: jakzal/phpqa:php8.1-alpine
  script:
    - composer install

lint:8.1:
  stage: qa
  image: jakzal/phpqa:php8.1-alpine
  script:
    - phplint . --exclude=vendor

phpunit:8.1:
  stage: qa
  image: jakzal/phpqa:php8.1-alpine
  script:
    - phpunit-8

.base-deploy:
  variables:
    PROJECT_DIR: $DIRECTORY_VGR_BUNDLES/CoreBundle/
  before_script:
    - apk update && apk upgrade
    - apk add openssh bash rsync
    - mkdir ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_ed25519
    - chmod 700 ~/.ssh/id_ed25519
    - eval $(ssh-agent -s)
    - ssh-add ~/.ssh/id_ed25519
    - ssh-keyscan -H 'gitlab.com' >> ~/.ssh/known_hosts
    - ssh-keyscan gitlab.com | sort -u - ~/.ssh/known_hosts -o ~/.ssh/known_hosts
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - rsync -rav --quiet --delete --exclude 'vendor' -e "ssh -p ${SSH_PORT}" --rsync-path="mkdir -p ${PROJECT_DIR} && rsync" ${CI_PROJECT_DIR}/ deploy@${SSH_HOST}:${PROJECT_DIR}

deploy-pp:
  extends: .base-deploy
  image: alpine:3
  stage: deploy-preprod
  environment:
    name: testing
  only:
    - develop
