cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - /vendor

stages:
  - build
  - qa
#  - deploy-preprod

build:7.4:
  stage: build
  image: jakzal/phpqa:php7.4-alpine
  script:
    - composer install

lint:7.4:
  stage: qa
  image: jakzal/phpqa:php7.4-alpine
  script:
    - phplint . --exclude=vendor

phpunit:7.4:
  stage: qa
  image: jakzal/phpqa:php7.4-alpine
  script:
    - phpunit-8

.base-deploy:
  variables:
    PROJECT_DIR: $DIRECTORY_VGR_BUNDLES/CoreBundle/
  script:
    - apk update && apk upgrade
    - apk add openssh bash rsync
    - eval $(ssh-agent -s)
    - mkdir ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - rsync -rav --quiet --delete --exclude 'vendor' -e "ssh -p ${PORT}" --rsync-path="mkdir -p ${PROJECT_DIR} && rsync" ${CI_PROJECT_DIR}/ deploy@${HOST}:${PROJECT_DIR}
#    - ssh -p ${PORT} ${HOST} cd /home/deploy/projects/api/ && composer install

deploy-pp:
  extends: .base-deploy
  image: alpine:3
  stage: deploy-preprod
  environment:
    name: testing
    url: https://api.projet-normandie.fr/
  only:
    - develop
