VideoGamesRecords\CoreBundle\Entity\Game:
  attributes:
    id:
      groups:
        - 'game.list'
        - 'game.read'
        - 'game.read.mini'
    name:
      groups:
        - 'game.list'
        - 'game.read'
        - 'game.read.mini'
    picture:
      groups:
        - 'game.read'
        - 'game.read.mini'
    groups:
      groups:
        - 'game.groups'
    status:
      groups:
        - 'game.read'
    publishedAt:
      groups:
        - 'game.list'
        - 'game.read'
    boolRanking:
      groups:
        - 'game.list'
        - 'game.read'
    nbChart:
      groups:
        - 'game.list'
        - 'game.read'
        - 'game.stats'
    nbPost:
      groups:
        - 'game.list'
        - 'game.read'
        - 'game.stats'
    nbPlayer:
      groups:
        - 'game.list'
        - 'game.read'
        - 'game.stats'
    nbTeam:
      groups:
        - 'game.read'
        - 'game.stats'
    serie:
      groups:
        - 'game.serie'
    badge:
      groups: []
    platforms:
      groups:
        - 'game.platforms'
    rules:
      groups:
        - 'game.read'
    slug:
      groups:
        - 'game.list'
        - 'game.read'
        - 'game.read.mini'
    forum:
      groups:
        - 'game.read'
    createdAt:
      groups: []
    updatedAt:
      groups: []
