VideoGamesRecords\CoreBundle\Entity\Player:
  attributes:
    id:
      groups:
        - 'player:read'
        - 'player:update'
    pseudo:
      groups:
        - 'player:read'
    createdAt:
      groups:
        - 'player:read'
    lastLogin:
      groups:
        - 'player:read'
    nbConnexion:
      groups:
        - 'player:read'
    presentation:
      groups:
        - 'player:read'
        - 'player:update'
    collection:
      groups:
        - 'player:read'
        - 'player:update'
    slug:
      groups:
        - 'player:read'
    status:
      groups:
        - 'player:status'
    avatar:
      groups:
        - 'player:read'
    country:
      groups:
        - 'player:country'
        - 'player:update'
    rankCountry:
      groups:
        - 'player:read'
    rankPointChart:
      groups:
        - 'player:read'
    averageChartRank:
      groups:
        - 'player:read'
    nbChart:
      groups:
        - 'player:read'
    nbChartMax:
      groups:
        - 'player:read'
    nbChartWithPlatform:
      groups:
        - 'player:read'
    nbChartProven:
      groups:
        - 'player:read'
    nbChartDisabled:
      groups:
        - 'player:read'
    pointChart:
      groups:
        - 'player:read'
    rankPointGame:
      groups:
        - 'player:read'
    pointGame:
      groups:
        - 'player:read'
    nbGame:
      groups:
        - 'player:read'
    nbVideo:
      groups:
        - 'player:read'
    rankMedal:
      groups:
        - 'player:read'
    chartRank0:
      groups:
        - 'player:read'
    chartRank1:
      groups:
        - 'player:read'
    chartRank2:
      groups:
        - 'player:read'
    chartRank3:
      groups:
        - 'player:read'
    rankCup:
      groups:
        - 'player:read'
    averageGameRank:
      groups:
        - 'player:read'
    gameRank0:
      groups:
        - 'player:read'
    gameRank1:
      groups:
        - 'player:read'
    gameRank2:
      groups:
        - 'player:read'
    gameRank3:
      groups:
        - 'player:read'
    rankProof:
      groups:
        - 'player:read'
    rankBadge:
      groups:
        - 'player:read'
    pointBadge:
      groups:
        - 'player:read'
    nbMasterBadge:
      groups:
        - 'player:read'
    team:
      groups:
        - 'player:team'
        - 'player:update'
    birthDate:
      groups:
        - 'player:read'
        - 'player:update'
    gender:
      groups:
        - 'player:read'
        - 'player:update'
    website:
      groups:
        - 'player:read'
        - 'player:update'
    youtube:
      groups:
        - 'player:read'
        - 'player:update'
    twitch:
      groups:
        - 'player:read'
        - 'player:update'
    discord:
      groups:
        - 'player:read'
        - 'player:update'
    displayPersonalInfos:
      groups:
        - 'player:read'
        - 'player:update'
    lastDisplayLostPosition:
      groups:
        - 'player:update'
    initial:
      groups:
        - 'player:read'
