VideoGamesRecords\CoreBundle\Entity\PlayerChartLib:
  attributes:
    id:
      groups:
        - 'player-chart-lib:read'
        - 'player-chart-lib:update'
    value:
      groups:
        - 'player-chart-lib:read'
        - 'player-chart-lib:insert'
        - 'player-chart-lib:update'
    libChart:
      groups:
        - 'player-chart-lib:read'
        - 'player-chart-lib:insert'
        - 'player-chart-lib:update'
    parseValue:
      groups:
        - 'player-chart-lib:read'
        - 'player-chart-lib:insert'
        - 'player-chart-lib:update'
