VideoGamesRecords\CoreBundle\Entity\Serie:
  attributes:
    id:
      groups:
        - 'serie:read'
    name:
      groups:
        - 'serie:read'
    slug:
      groups:
        - 'serie:read'
    status:
      groups:
        - 'serie:read'
    nbGame:
      groups:
        - 'serie:read'
    description:
      groups:
        - 'serie:read'
    nbChart:
      groups:
        - 'serie:read'
    status.value:
      groups:
        - 'serie:read'
    games:
      groups:
        - 'serie:games'
