VideoGamesRecords\CoreBundle\Entity\TeamRequest:
  attributes:
    id:
      groups:
        - 'team-request:read'
        - 'team-request:update'
    team:
      groups:
        - 'team-request:read'
        - 'team-request:insert'
    player:
      groups:
        - 'team-request:read'
        - 'team-request:insert'
    status:
      groups:
        - 'team-request:read'
        - 'team-request:update'
    createdAt:
      groups:
        - 'team-request:read'

