VideoGamesRecords\CoreBundle\Entity\Team:
  attributes:
    id:
      groups:
        - 'team.read'
        - 'team.read.mini'
        - 'team.put'
    libTeam:
      groups:
        - 'team.read'
        - 'team.read.mini'
        - 'team.put'
    slug:
      groups:
        - 'team.read'
        - 'team.read.mini'
    tag:
      groups:
        - 'team.read'
        - 'team.read.mini'
        - 'team.put'
    status:
      groups:
        - 'team.read'
        - 'team.put'
    siteWeb:
      groups:
        - 'team.read'
        - 'team.put'
    logo:
      groups:
        - 'team.read'
        - 'team.read.mini'
        - 'team.profile'
    leader:
      groups:
        - 'team.leader'
        - 'team.put'
      max_depth: 1
    nbPlayer:
      groups:
        - 'team.read'
    rankPointChart:
      groups:
        - 'team.rank.pointChart'
    pointChart:
      groups:
        - 'team.rank.pointChart'
    rankPointGame:
      groups:
        - 'team.rank.pointGame'
    pointGame:
      groups:
        - 'team.rank.pointGame'
    nbGame:
      groups:
        - 'team.rank.pointGame'
    rankMedal:
      groups:
        - 'team.rank.medal'
    chartRank0:
      groups:
        - 'team.rank.medal'
    chartRank1:
      groups:
        - 'team.rank.medal'
    chartRank2:
      groups:
        - 'team.rank.medal'
    chartRank3:
      groups:
        - 'team.rank.medal'
    rankCup:
      groups:
        - 'team.rank.cup'
    gameRank0:
      groups:
        - 'team.rank.cup'
    gameRank1:
      groups:
        - 'team.rank.cup'
    gameRank2:
      groups:
        - 'team.rank.cup'
    gameRank3:
      groups:
        - 'team.rank.cup'
    rankBadge:
      groups:
        - 'team.rank.badge'
    pointBadge:
      groups:
        - 'team.rank.badge'
    nbMasterBadge:
      groups:
        - 'team.rank.badge'
    teamBadge:
      groups:
        - 'team.badges'
    teamGame:
      groups:
        - 'team.game'
      max_depth: 1
    createdAt:
      groups:
        - 'team.read'
    players:
      groups:
        - 'team.players'

